using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Engine.Backend.Models
{
    [DataModel("tblemployeerole")]
    public class EmployeeRole
    {
        [DataField("roleid", QueryParamType.Integer), AutoGenerated, PrimaryKey]
        public int? RoleId { get; set; }

        [DataField("name", QueryParamType.VarChar)]
        public string Name { get; set; }

        [DataField("description", QueryParamType.VarChar)]
        public string Description { get; set; }

        public override string ToString()
        {
            return Name;
        }

        public override bool Equals(object obj)
        {
            return obj is EmployeeRole && (obj as EmployeeRole).Name.Equals(Name);
        }

        public override int GetHashCode()
        {
            return Name.GetHashCode();
        }

        public static bool operator  ==(EmployeeRole left, EmployeeRole right)
        {
            return left.Equals(right);
        }

        public static bool operator  !=(EmployeeRole left, EmployeeRole right)
        {
            return !left.Equals(right);
        }
    }
}
