using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Engine.Backend.Models
{
    [DataModel("tblemployeerole")]
    public class EmployeeRole
    {
        [DataField("roleid", QueryParamType.Integer), AutoGenerated, PrimaryKey]
        public int? RoleId { get; set; }

        [DataField("name", QueryParamType.VarChar)]
        public string Name { get; set; }

        [DataField("description", QueryParamType.VarChar)]
        public string Description { get; set; }
    }
}
