using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Engine.Backend.Models
{
    [DataModel("tblgenre")]
    public class Genre
    {
        [DataField("genreid", QueryParamType.Integer), AutoGenerated, PrimaryKey]
        public int? GenreId { get; set; }

        [DataField("title", QueryParamType.VarChar)]
        public string Title { get; set; }

        [DataField("description", QueryParamType.Text)]
        public string Description { get; set; }

        [DataField("isactive", QueryParamType.Boolean)]
        public bool? IsActive { get; set; }
    }
}
