using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Engine.Backend.Models
{
    [DataModel("tblsubscription")]
    public class Subscription
    {
        [DataField("subscriptionid", QueryParamType.Integer), AutoGenerated, PrimaryKey]
        public int? SubscriptionId { get; set; }

        [DataField("customerid", QueryParamType.Integer), ForeignKey("tblcustomer", "customerid")]
        public Customer CustomerId { get; set; }

        [DataField("seriesid", QueryParamType.Integer), ForeignKey("tblblockSeries", "seriesid")]
        public BlockSeries SeriesId { get; set; }

        [DataField("startedon", QueryParamType.Date)]
        public DateTime? StartedOn { get; set; }

        [DataField("endedon", QueryParamType.Date), Nullable]
        public DateTime? EndedOn { get; set; }

        [DataField("billingtype", QueryParamType.VarChar)]
        public string BillingType { get; set; }

        [DataField("shippingaddress", QueryParamType.Integer), ForeignKey("tbladdress", "addressid")]
        public Address ShippingAddress { get; set; }
    }
}
