using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Engine.Backend.Models
{
    [DataModel("tbltransfer")]
    public class Transfer
    {
        [DataField("transferid", QueryParamType.Integer), AutoGenerated, PrimaryKey]
        public int? TransferId { get; set; }

        [DataField("storeid", QueryParamType.Integer), ForeignKey("tblmortarstore", "storeid")]
        public MortarStore StoreId { get; set; }

        [DataField("transferdate", QueryParamType.Date)]
        public DateTime? TransferDate { get; set; }
    }
}
