using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Sandbox.Backend.Models
{
    [DataModel("tbladdress")]
    public class Address
    {
        [DataField("addressid", QueryParamType.Integer), PrimaryKey, AutoGenerated]
        public int? Id { get; set; } = -1;

        [DataField("streetaddress", QueryParamType.VarChar)]
        public string StreetAddress { get; set; } = null;

        [DataField("country", QueryParamType.VarChar)]
        public string Country { get; set; } = null;

        [DataField("state", QueryParamType.VarChar)]
        public string State { get; set; } = null;

        [DataField("apartmentnumber", QueryParamType.Integer), Nullable]
        public int? AptNum { get; set; } = null;

        [DataField("specialrequests", QueryParamType.Text), Nullable]
        public string Requests { get; set; } = null;

        [DataField("postalcode", QueryParamType.VarChar)]
        public string PostalCode { get; set; } = null;
    }
}
