using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Sandbox.Backend.Models
{
    [DataModel("tblbillinginfo")]
    public class BillingInfo
    {
        [DataField("billinginfoid", QueryParamType.Integer), AutoGenerated, PrimaryKey]
        public int? BillingInfoId { get; set; }

        [DataField("paymenttype", QueryParamType.VarChar)]
        public string PaymentType { get; set; }

        [DataField("address", QueryParamType.Integer), ForeignKey("tbladdress", "addressid"), Nullable]
        public int? Address { get; set; }

        [DataField("accountnum", QueryParamType.Long), Nullable]
        public long? AccountNum { get; set; }

        [DataField("token", QueryParamType.VarChar), Nullable]
        public string Token { get; set; }
    }
}
