using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Sandbox.Backend.Models
{
    [DataModel("tblblock")]
    public class Block
    {
        [DataField("blockid", QueryParamType.Integer), AutoGenerated, PrimaryKey]
        public int? BlockId { get; set; }

        [DataField("seriesid", QueryParamType.Integer), ForeignKey("tblblockseries", "seriesid")]
        public BlockSeries SeriesId { get; set; }

        [DataField("title", QueryParamType.VarChar)]
        public string Title { get; set; }

        [DataField("description", QueryParamType.Text)]
        public string Description { get; set; }
    }
}
