using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Sandbox.Backend.Models
{
    [DataModel("tblemployee")]
    public class Employee
    {
        [DataField("id", QueryParamType.Integer), AutoGenerated, PrimaryKey]
        public int ID { get; set; }

        [DataField("firstname", QueryParamType.VarChar)]
        public string FirstName { get; set; }

        [DataField("lastname", QueryParamType.VarChar)]
        public string LastName { get; set; }

        [DataField("email", QueryParamType.VarChar), Nullable]
        public string Email { get; set; }

        [DataField("phone", QueryParamType.VarChar), Nullable]
        public string Phone { get; set; }

        [DataField("addressid", QueryParamType.Integer), ForeignKey("tbladdress", "id")]
        public Address Address { get; set; }
    }
}
