using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Sandbox.Backend.Models
{
    [DataModel("tblorder")]
    public class Order
    {
        [DataField("orderid", QueryParamType.Integer), AutoGenerated, PrimaryKey]
        public int? OrderId { get; set; }

        [DataField("dateordered", QueryParamType.Date)]
        public DateTime? DateOrdered { get; set; }

        [DataField("orderedby", QueryParamType.Integer), ForeignKey("tblemployees", "employeeid")]
        public int? OrderedBy { get; set; }

        [DataField("supplierid", QueryParamType.Integer), ForeignKey("tblsuppliercontact", "contactid")]
        public int? SupplierId { get; set; }
    }
}
