using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Sandbox.Backend.Models
{
    [DataModel("tblsuppliercontact")]
    public class SupplierContact
    {
        [DataField("contactid", QueryParamType.Integer), AutoGenerated, PrimaryKey]
        public int? ContactId { get; set; }

        [DataField("company", QueryParamType.Integer), ForeignKey("tblsupplier", "supplierid")]
        public Supplier Company { get; set; }

        [DataField("firstname", QueryParamType.VarChar)]
        public string FirstName { get; set; }

        [DataField("lastname", QueryParamType.VarChar)]
        public string LastName { get; set; }

        [DataField("phonenumber", QueryParamType.Long)]
        public long? PhoneNumber { get; set; }

        [DataField("email", QueryParamType.VarChar)]
        public string Email { get; set; }
    }
}
