using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerdBlock.Sandbox.Backend.Models
{
    [DataModel("tblsupplier")]
    class Supplier
    {
        [DataField("supplierid", QueryParamType.Integer), AutoGenerated, PrimaryKey]
        public int? SupplierId { get; set; }

        [DataField("company", QueryParamType.VarChar)]
        public string Company { get; set; }

        [DataField("address", QueryParamType.Integer), ForeignKey("tbladdress", "addressid")]
        public int? Address { get; set; }

        [DataField("phone", QueryParamType.Long)]
        public long? Phone { get; set; }
    }
}
